# Main CI script
#
# TODO
# - Run synthesis with 1 minute timeout

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  verilog-test:
    runs-on: ubuntu-22.04
    container:
      image: barabas5532/crush-ci:2
    strategy:
      matrix:
        target:
          - sim_inst_immediate_decode
          - sim_memory
          - sim_alu
          - sim_load_store
          # sim_cpu is not a testbench, but a target for RISCOF testing, so it
          # is not included here
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up python environment
        run: |
          apt-get install -y python3-venv
          python -m venv .venv
          . .venv/bin/activate
          python -m pip install -r requirements.txt
          # Every step runs in its own shell. Activating the venv really just
          # modifies the path. Persist the modified path, so that other steps
          # also use the venv.
          echo PATH=$PATH >> $GITHUB_ENV
      - name: Run test
        run: |
          script/init.sh
          fusesoc run --target ${{ matrix.target }} crush
  verilog-lint:
    runs-on: ubuntu-22.04
    container:
      image: barabas5532/crush-ci:2
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up python environment
        run: |
          apt-get install -y python3-venv
          python -m venv .venv
          . .venv/bin/activate
          python -m pip install -r requirements.txt
          # Every step runs in its own shell. Activating the venv really just
          # modifies the path. Persist the modified path, so that other steps
          # also use the venv.
          echo PATH=$PATH >> $GITHUB_ENV
      - name: Run lint
        run: |
          script/init.sh
          fusesoc run --target lint crush
  riscof-test:
    runs-on: ubuntu-22.04
    container:
      image: barabas5532/crush-ci:2
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up python environment
        run: |
          apt-get install -y python3-venv
          python -m venv .venv
          . .venv/bin/activate
          python -m pip install -r requirements.txt
          # Every step runs in its own shell. Activating the venv really just
          # modifies the path. Persist the modified path, so that other steps
          # also use the venv.
          echo PATH=$PATH >> $GITHUB_ENV
      - name: Run RISCOF
        run: |
          script/init.sh
          script/compliance.sh
